# Generated by Django 4.0.4 on 2022-06-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_profile_avatar_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaincredentials',
            name='domain',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='domaincredentials',
            name='id_contract',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
